### ISSUE TITLE
Check for zero address in setPrivileged

### ISSUE THREAD

**Issue by rbharath** [computablelabs/goest#131]
The `setPrivileged` function in `MarketToken.vy` and `Voting.vy` should check that its argument addresses are not `ZERO_ADDRESS`. It is not semantically valid to set these to `ZERO_ADDRESS` so the additional check will prevent accidental errors.

**Comment by robrobbins** [comment]
Hmm. I _am_ coding this up. I _am not_ convinced it means anything.

Yes, it _is_ incorrect that it's possible to call these with `0x0000`.  This "fix" would stop that. 
However
You could also call these with completely incorrect addresses and fuck up your whole market. There is no fix in the world for that (that i would implement). In that case you must re-deploy the entire set of contracts.
So.
I don't see any _real_ value in putting in a fix for an error that can be corrected vs leaving one that cannot.
This is meaningless and likely to get a `No` from me.
< / discuss >

**Comment by robrobbins** [comment]
not doing.
