### ISSUE TITLE
Remove EtherToken initial balance

### ISSUE THREAD

**Issue by rbharath** [computablelabs/goest#135]
At present, `EtherToken.vy` can be initialized with an initial balance. This could lead to an attack where a malicious market creator can withdraw `EtherToken` that other users have deposited. To close off this attack window, the constructor for `EtherToken` (https://github.com/computablelabs/goest/blob/master/contracts/EtherToken.vy#L19) should be altered so that it no longer accepts an initial balance:
```
@public
def __init__():
  self.decimals = 18
  self.symbol = "CET"
  self.supply = 0
```

**Comment by robrobbins** [comment]
no need to set `self.supply = 0` in the CTOR, it already will default to zero via the state var declaration.

**Comment by robrobbins** [comment]
#142
