### ISSUE TITLE
Market Contract

### ISSUE THREAD

**Issue by robrobbins** [computablelabs/goest#14]
A modified Registry

**Comment by robrobbins** [comment]
@rbharath can you identify the changes from the v1 Registry that need to go in and list them here?

**Comment by rbharath** [comment]
Changes needed:
- Rename `Registry.sol` to `Market.sol`
- Add a "reserve" to the Market. This reserve will hold `NetworkToken` that is paid in by investors who want to take positions in market and will pay out to people who want to exit market.
- New method `Market.invest(amount)` (or alternatively `Market.enter()`) allowing an investor to enter the market
- New method `Market.divest()` (or alternatively `Market.exit()`) allow any token holder to exit the market

**Comment by rbharath** [comment]
We'll need additional changes to allow for utility payments `T_util` and for queries. I'll add on more comments here as that becomes clearer

**Comment by rbharath** [comment]
For `T_util`, we will have the dapp report which data-elements were accessed in queries. For this, we will add a method:
- New method `Market.report_accessed(element_id)` that can only be called by the owner of the market. This element mints `T_util` tokens and gifts them to owner of `element_id`.

**Comment by rbharath** [comment]
For queries, in v2, we're going to have a very simple payment model. One flat payment to authorize query access. Dapps decide what queries are supported (different apps can support different types of queries), but for now only one payment method. When the Dapp determines enough queries have been answered, query authorization is revoked for the user, who has to now pay again.

- New method `Market.pay_for_query_access(amount)` called by user to get query access.
- New method `Market.revoke_query_access(user)` called by owner of market to revoke query access for user once enough queries have been answered.

**Comment by rbharath** [comment]
For algorithmic price discovery, we will need a method to get the current price:

- New method `Market.get_current_investment_price()` that returns the current NetworkToken/MarketToken exchange rate from the price curve.

**Comment by rbharath** [comment]
For handling potential data flood attacks and the dilution effect, a couple changes
- Token holders are now in two classes, data owner and investor
- New method `Market.convert_to_investor()` to convert a data owner to an investor.
- Only investors can call `Market.exit()`
- Price curve is now issued against total # investor-class tokens.

**Comment by robrobbins** [comment]
Market is likely done for v3. Size is becoming a factor as it is approaching 25k. Freezing any further functionality as of latest commit: https://github.com/computablelabs/goest/commit/b32dd8346c4196ed2a665d25761ec815f694b7aa
