### ISSUE TITLE
Market Reserve

### ISSUE THREAD

**Issue by rbharath** [computablelabs/goest#20]
Each Data market should hold a reserve of Network Token (#19). This issue is a dependency for #14. Here's a brief summary of methods that interact with reserve

- `Market.invest()` adds investor Network Token to reserve and mints and returns Market Token to investor. Pricing dictated by price curve.
- `Market.divest(num_tokens)` allows investor class token holders (see #14) to burn Market Token and withdraw Network Token from the reserve.
  - `divest()` first checks that its caller is an investor class tokenholder. If so, it computes the fractional ownership this investor has (`num_tokens/total_num_investor_tokens`). For example, if `num_tokens=5` and `total_num_investor_tokens=100`, this would be 5% fractional ownership. Then `num_tokens` market tokens are burned. Then the fractional part of the reserve belonging to this investor is transferred to the investor. For example, in the case above, 5% of the reserve would be transferred to the investor's address.

**Comment by robrobbins** [comment]
Reserve is kept via the Ethertoken contract as of now. Will not change for V3. Closing as done.
