### ISSUE TITLE
Algorithmic Price Curve

### ISSUE THREAD

**Issue by rbharath** [computablelabs/goest#21]
The price curve dictates the conversion rate between Network Token and Market Token. Note this issue is a dependency for #14. Methods that interact with the price curve

- `Market.get_current_investment_price()` reports the current NetworkToken/MarketToken conversion rate. Mathematically, the first version will be a linear function. That is, ~`Market.get_current_investment_price() = base_conversion_rate + conversion_slope * Market.get_total_number_investor_tokens()`~ `Market.get_current_investment_price() = base_conversion_rate + conversion_slope * Market.get_reserve_size()` where `base_conversion_rate` and `conversion_slope` are parameters defined by the market creator. 
- `Market.get_reserve_size()` returns the size of current market reserve in NetworkToken
- `Market.invest()` consults `Market.get_current_investment_price()` to perform the exchange.

Note that the linear form of the price curve above is not necessarily set in stone. It's likely that future iterations will allow users to choose alternate forms of the price curve.

**Comment by rbharath** [comment]
Updated the specification of the algorithmic price curve above to account for a potential attack @rgrchen found.

@robrobbins The algorithmic price curve is now dependent on the size of the reserve and not on the number of investor class tokens.

**Comment by robrobbins** [comment]
Buy and Sell curves _likely_ set for V3 as of now
