### ISSUE TITLE
Separating Investor Class and Data Owner Class in Market

### ISSUE THREAD

**Issue by rbharath** [computablelabs/goest#22]
The Data Market (#14) will have two classes of token holder, investors and data owners. The existing `Registry.sol` contract tracks only listings and challenges, and doesn't track investors. A new data `mapping` will have to be added that tracks the class of each token holder in the data market. In addition, new token holders will have to be entered into this `mapping`. Methods that will interact with `mapping`

- `Market.invest()` will add a new investor class member (if not already added)
- `Market.divest()` will check if given member is investor class and remvoe them if so
- `Market.apply()` will add the given member to the data owner class (Note: perhaps a data owner must be whitelisted). (This method is currently called `Registry.apply()`)
- `Market.exit()` will remove a data owner if they are not present any further listings. (This method is currently called `Registry.exit()`).

**Comment by rbharath** [comment]
I've marked this as a Protovol V2 milestone, but if implementation starts to look tricky, may perhaps shift to V3.

**Comment by rbharath** [comment]
There should be a method which allows data owner class token holders to convert themselves into investor class holders:

- `Market.convert_to_investor()`: Converts self to investor class token holder. Investor class token holders can't own datapoints, so ownership of these datapoints is reverted to the Market contract and all future query payments for these datapoints is made directly into reserve.

**Comment by robrobbins** [comment]
There is going to be `convertListing` which allows makers to "cash out" a listing. Given that a maker has no listings anymore they are free to invest afterwards. Not going to provide a protocol level sugar-coat for this whole process (apps/dapps might)

**Comment by robrobbins** [comment]
this is done for v3
