### ISSUE TITLE
Councils for Data Markets

### ISSUE THREAD

**Issue by rbharath** [computablelabs/goest#28]
Currently, votes in `Market.sol` are performed by all token holders. This voting scheme should be modified so that only "council members" vote on actions. Determination of council membership is (for now), automatic. `T_council` is a threshold (set in `MarketToken`). If a member of the data market holds market tokens `T_member > T_council`, then that member becomes a council member and can vote. Only council votes should be used to perform registry actions.

**Comment by robrobbins** [comment]
NOTE: in v3 only council members can vote.

**Comment by robrobbins** [comment]
yes. it will not be automatic addition however.

a method `applyToCouncil` will be added to the `Voting` contract such that any `stakeholder` may apply for council membership and be accepted if their T_member > T_council

**Comment by robrobbins** [comment]
worth noting that _removal_ from the council is automatic however and must be checked anywhere market tokens are spent, burned etc...

**Comment by robrobbins** [comment]
false. this all goes away. there is no council. 

there is only checks for market_token_balance > council_threshold

this has voting ramifications, but that's a separate issue

**Comment by robrobbins** [comment]
there is no council and no threshold. only staked voting
