### ISSUE TITLE
Authorized backends for Markets

### ISSUE THREAD

**Issue by rbharath** [computablelabs/goest#30]
Each data market will maintain a list of authorized backend systems. A full vote of the council (#28) will be needed to add, remove, or authorize backends.

- `Market.get_backend_system()`: Returns list of authorized backend systems for the market
- `Market.add_backend_system(id)`: This must be authorized by a vote of the council.
- `Market.remove_backend_system(id)`: This must be authorized by a vote of the council

**Comment by robrobbins** [comment]
let's update this

**Comment by rbharath** [comment]
The key responsibilities for a backend are:

- Affirming that listings are stored. This must be done before the listing is listed on the market.
- Claim a secure computing job. 
- Report completion of the secure computing job and zero-out any outstanding user payments for that job.

**Comment by robrobbins** [comment]
done as of #71
