### ISSUE TITLE
Query Pricing

### ISSUE THREAD

**Issue by rbharath** [computablelabs/goest#32]
This is a first stab at spec-ing out the query pricing scheme. Will update this spec as we gain clarity.

- Listing owners can set an access cost for their listing (in network token). For listings which are owned by the market itself, a council vote is required to update this access cost.
  - `Market.set_access_cost(listing)`: Callable by listing owner to set price.
  - `Market.get_access_cost(listing)`: Getter to view cost.
- For now, each market can only support a fixed number of queries: `query_1, query_2,..., query_n`. A backend system can set its asking price to run computation for this query. Each listing will access some specified subset of listings in market.
  - `Market.set_query_compute_cost(query_i, backend_j, cost)`: `query_i` is one of supported queries. `backend_j` is some approved backend. `cost` is in network token.
  - `Market.get_query_compute_cost(query_i)`: Returns cheapest cost available (TODO: More refined scheme?)
  - `Market.report_listings_accessed(query_i)`: Reports the listings which the given query will access. (TODO: How does this change as new listings are added?)
- Each query causes some loss in data privacy. A charge is leveled to account for this cost. This charge may be adaptive and depend on history of past queries by given user (TODO: More details)
  - `Market.get_privacy_cost(query_i)`: Cost will depend on user invoking and past queries they've run.
- The total cost for running a query is the sum of all these terms. Here's some python-esque pseudo-code
```
def get_total_cost():
  cost = 0
  query = Query to run
  listings_accessed = Market.listings_accessed(query)
  # Data access cost
  for listing in listings_accessed:
    cost += Market.get_access_cost(listing)
  # Query compute cost (assume one backend)
  cost += Market.get_query_compute_cost(query)
  # Privacy cost
  cost += Market.get_privacy_cost(query)
```

Please leave comments below. Will update the spec at this top posting as clarity is gained.

**Comment by rgrchen** [comment]
"For listings which are owned by the market itself" == orphan datapoints?
Also, just a note that listing owners _can_  set the data access price but _don't have to_. Said differently, `Market.set_access_cost(listing)` is callable by listing owner but maybe not just the listing owner. Or there needs to be some other way price gets set at the product level. Product context here is that I'm dubious most users will want to actually manage and manually set access prices, though we want to provide that flexibility at the protocol level.

**Comment by rbharath** [comment]
Listings owned by market itself are datapoints whose owners have converted to investor class (and traded in ownership of their listings)

Let's dig into permissions a bit more offline. Agree some way to set price at product level needed, but not sure what the right mechanism is.

**Comment by rbharath** [comment]
Closing in favor of #48 which is more up to date
