### ISSUE TITLE
Query Payment Split

### ISSUE THREAD

**Issue by rbharath** [computablelabs/goest#33]
For query payments that come in (#32), a portion of the query payment (the "rake") is paid into the reserve, a portion is paid to listing owners, and a portion is paid to the backend. 

- The owner of a listing is paid the access cost they set with `Market.set_access_cost(listing)`
- The backend system is paid the compute cost they set with `Market.set_query_compute_cost(query)`
- The reserve is paid the privacy cost `Market.get_privacy_cost(query)`

TODO: This scheme isn't finalized yet. Leave comments below and will update this top level specification.

**Comment by rgrchen** [comment]
Work session on how `reserve`<>`Market.get_privacy_cost(query)` next time? Privacy should influence overall cost but just not sure it should be so directly impactful on the "rake"

**Comment by rbharath** [comment]
Good suggestion. We should have a principled take on the `reserve<> Market.get_privacy_cost(query)` relationship.

**Comment by robrobbins** [comment]
this is kind of a dupe and mostly is answered by #71. closing as another issues captures the remaining work on payment splits
