### ISSUE TITLE
Data Utilization Records

### ISSUE THREAD

**Issue by rbharath** [computablelabs/goest#35]
The market is responsible for maintaining record of which queries have accessed which datapoints. The backend system will report datapoints accessed by a given query to the market.

- `Market.report_listings_accessed(query_i)`: Called by backend system after running a query. This information is stored on-chain. For reasons of gas, this may just be a simple count; each listing may maintain a simple count field which is incremented for each additional query that accesses it. (See also discussion in #32 around pricing)

**Comment by robrobbins** [comment]
nope. this count is not needed as:
1. logs exist
2. listings have a kept `rewards` and the number can be divined by dividing the rewards by the list_access price (minus the initial listing reward)
