### ISSUE TITLE
Bug in Market.invest? - calculating taken qty

### ISSUE THREAD

**Issue by reichiang** [computablelabs/goest#43]
Shouldn't this just be:
`uint taken = offered.sub(remainder);`

https://github.com/computablelabs/goest/blob/686b0701e38890dac4785ab1081417ec785e5bac/contracts/Market.sol#L235

**Comment by robrobbins** [comment]
i think you are correct. `invest` and `divest` will be my focus next week (flushing them out, writing specs) so i'll make this change then. thx

**Comment by robrobbins** [comment]
fixed
