### ISSUE TITLE
Output Cost Per Byte for secure computation

### ISSUE THREAD

**Issue by rbharath** [computablelabs/goest#47]
For secure computations run against the market, users are charged per byte of output. This means that we should add a new parameterizer term:

- `COST_PER_OUTPUT_BYTE`: This is denominated in wei

Users will pay for secure computation by invoking the following method

- `Market.pay_for_secure_compute(uint num_output_bytes)`: This method will charge the user `num_output_bytes * COST_PER_OUTPUT_BYTE` wei and will store the `(user, num_output_bytes)` in the contract.

We also need to provide an endpoint for the backend to check how many bytes a user has paid for

- `Market.get_num_output_bytes(user)`: This method returns the number of output bytes this user has paid for. If the user hasn't paid anything, returns 0

Once the secure compute has been performed, the backend will report this to contract which will reset `num_output_bytes` for the user to zero

- `Market.reset_num_output_bytes(user)`: Called by backend after computer performed.

**Comment by robrobbins** [comment]
done as of #71
