### ISSUE TITLE
Secure Computation Payments

### ISSUE THREAD

**Issue by rbharath** [computablelabs/goest#48]
Users pay for secure compute (see #47). The payment is split between the backend, listing owners, and the reserve. The relative proportionality of the split is controlled by parameterizer variables:

- `BACKEND_PAYMENT_PERCENT`: Percentage between 0 and 100
- `LISTING_OWNER_PAYMENT_PERCENT`: Percentage between 0 and 100. In 0.3, we assume all listings are used equally, so split between all listing owners in the market.
- `RESERVE_PAYMENT_PERCENT`: Percentage between 0 and 100.

The invariant is:

` BACKEND_PAYMENT_PERCENT + LISTING_OWNER_PAYMENT_PERCENT + RESERVE_PAYMENT_PERCENT == 100`

In addition, secure compute jobs result in minting of new tokens which are awarded to listing owners. The amount minted is controlled by a parameterizer variable

- `SECURE_COMPUTE_MINT_AMOUNT`: Denominated in market token wei.

In 0.3, we assume that each secure compute job uses all listings, so this payment is split across all listing owners.

**Comment by robrobbins** [comment]
My current working theories and musings:

1. reserve_pct is not needed. it is implicit in that a different invariant, one stating that `backend_pct + maker_pct < 100`. That delta _is_ the reserve_pct.
2. `access_reward` is the P11r attribute for what is paid out to a listing's rewards on use

**Comment by robrobbins** [comment]
#71 handles all of this except access_reward which is forthcoming

**Comment by robrobbins** [comment]
#100
