### ISSUE TITLE
Market Divest

### ISSUE THREAD

**Issue by rbharath** [computablelabs/goest#51]
An investor in a `Market` has the option to divest from the market. Upon calling the `divest()` method, the following set of operations happens:

- All `MarketToken` owned by this investor is burned. That is, `markettoken[balances[investorAddress]]`
- Let's suppose that the investor originally owned `c` `MarketToken` out of a total supply of `N` market token. Let `reserve` denote the total amount of `EtherToken` in the reserve. Then `(c * reserve / N)` `EtherToken` is transferred to the investor. Here, both `c` and `N` ~are denominated in `MarketToken` gwei~ (see clarification below) and `reserve` in `EtherToken` wei. This difference in units should keep the dust relatively small. 

If a non-investor calls this method, it should fail and do nothing. In addition, this method should check to see if this investor has any `MarketToken` staked/locked. Should fail if so

**Comment by robrobbins** [comment]
I think we have this one nailed down. @rbharath you can make that call

**Comment by robrobbins** [comment]
done for V3
