### ISSUE TITLE
cost_per_byte stability equations

### ISSUE THREAD

**Issue by rbharath** [computablelabs/goest#70]
There are a couple of stability equations that should govern `cost_per_byte` and `compute_reward`:

1. `divestPrice(compute_reward) < maker_pct * cost_per_byte / N_listings`: This is a rough inflation stability equation. It says roughly that the minted maker utilization rewards will have current market value (governed by the divestment price) that is less than what was added to the reserve. Without this property, perennial inflation could result.
2. `cloud-compute-cost < DollarValue(backend_pct * cost_per_byte * N_bytes)`: For a backend, the dollar value of their payment for a compute job is `DollarValue(backend_pct * cost_per_byte * N_bytes)` where `DollarValue` is the current ETH/$ conversion rate. If this payment doesn't cover the base payment to the cloud provider for compute, the backend is losing money on the compute job.

The council is responsible for actively governing so that these stability relations don't fall askew

**Comment by robrobbins** [comment]
is `reserve_pct` needed anywhere? esp since at `purchaseCompute` time the `backend_pct` is taken out (paid to backend's acct) and the _rest_ is put into reserve.

**Comment by robrobbins** [comment]
explicit reserve_pct is removed as it is now the implicit delta of 100 - maker_pct + backend_pct

**Comment by robrobbins** [comment]
i think we are done here @rbharath. close this if so

**Comment by rbharath** [comment]
Yes, I think we're done here. Equation 1 is addressed by the new maker investment structure and equation 2 has partially been punted out.
