### ISSUE TITLE
Eliminating Hash Collisions in Parameterizer.getHash()

### ISSUE THREAD

**Issue by rbharath** [computablelabs/goest#85]
The current Parameterizer.getHash method generates a hash as follows:

`keccak256(convert((param + value), bytes32))`

https://github.com/computablelabs/goest/blob/master/contracts/Parameterizer.vy#L129

This can collide with tuples (1,2) (2,1) for (param, value) for example. There are a couple possible fixes:

1. Do H(H(param) || H(value)) where you chain hashes.
2. Move hashing off chain to user responsibility

**Comment by rbharath** [comment]
Also need to change here: https://github.com/computablelabs/goest/blob/master/contracts/Parameterizer.vy#L187

**Comment by robrobbins** [comment]
#94
