### ISSUE TITLE
Ensure setPrivileged is called only once.

### ISSUE THREAD

**Issue by rbharath** [computablelabs/goest#89]
https://github.com/computablelabs/goest/blob/master/contracts/MarketToken.vy#L166

This TODO needs to be implemented to make sure that theft of factory key can't take down deployed contracts

**Comment by rbharath** [comment]
Should do this here as well:

https://github.com/computablelabs/goest/blob/master/contracts/Voting.vy#L56

**Comment by rbharath** [comment]
Here as well:

https://github.com/computablelabs/goest/blob/master/contracts/Datatrust.vy#L91

**Comment by robrobbins** [comment]
so the actual code is the easy part:

`assert self.foo_address == ZERO_ADDRESS`

the _fun_ part in this ticket is that many specs will need to be re-written which utilize the contracts "upstream" which have permission to do things (like create a voting candidate)

that, or, you can just introduce another deployed `FooContract` whose privileged addresses are something you choose for that spec (like an authUser for test simplicity).

either is ok

**Comment by rbharath** [comment]
Closed by #115
