### ISSUE TITLE
Rename CONVERSION_RATE to PRICE_FLOOR

### ISSUE THREAD

**Issue by rbharath** [computablelabs/goest#95]
At present, the price floor parameter is called `CONVERSION_RATE`. Semantically, this is the price floor for the investment function so should be renamed `PRICE_FLOOR`

https://github.com/computablelabs/goest/blob/master/contracts/Parameterizer.vy#L6

This will require some additional changes to the contracts.

**Comment by robrobbins** [comment]
also `QUORUM` to `PLURALITY`

**Comment by robrobbins** [comment]
#101
