### ISSUE TITLE
Invest Unit Multiplier should be 10^9

### ISSUE THREAD

**Issue by rbharath** [computablelabs/goest#96]
The `getInvestmentPrice()` method uses a unit multiplier of 10^18. 

https://github.com/computablelabs/goest/blob/master/contracts/Investing.vy#L51

This is used in `invest()` at 

https://github.com/computablelabs/goest/blob/master/contracts/Investing.vy#L63

This looks to be wrong on some testing of the following scenario:

- Pick `PRICE_FLOOR = 10 gwei`. This sets 10 ETH : 1 MKT as the initial conversion
- Set `SPREAD = 100` (so no spread)
- Creator block size: 1 MKT
- Investor 1 invests 10 ETH.
  - A call to `getInvestmentPrice()` (which should return price in ETH wei to purchase 1 gwei MKT) returns:
    - `= rate + ((spread * reserve * 10^18) / (100 * total))`
    - `= 10*10^9 + (100 * 0 * 10^18) / (100 * 2 * 10^18)`  
    - `= 10*10^9` (that is, purchasing 1 gwei of MKT requires 10 gwei ETH)
  - The minted amount of MKT is now
    - `= (offer / price) * 10^9`
    - `= ((10 * 10^18) / (10 * 10^9)) * 10^9`
    - `= 10^9 * 10^9`
    - `= 10^18` (that is, 1 MKT minted)
- Investor 1 now holds: 1 MKT
- Creator now holds: 1 MKT
- Reserve now holds 10 ETH, total MKT cap is 2 MKT
- A call to `getInvestmentPrice()` is now: 
  - `= rate + ((spread * reserve * 10^18) / (100 * total))`
  - `= 10*10^9 + (100 * (10 * 10^18) * 10^18) / (100 * 2 * 10^18)`
  - `= 10*10^9 + (10 * 10^18) / 2`
  - `= 10*10^9 + 5 * 10^18`
  - `~ 5 * 10^18`

That is, the price to purchase 1 gwei of MKT is now 5 ETH! If we instead use a unit multiplier of 10^9 in `getInvestmentPrice()`:
  - `= rate + ((spread * reserve * 10^9) / (100 * total))`
  - = `10*10^9 + (100 * (10 * 10^18) * 10^9) / (100 * 2 * 10^18) `
  - `= 10*10^9 + (10 * 10^9) / 2 `
  - `= 10*10^9 + 5 * 10^9`
  - `= 15 * 10^9`

Then the price to purchase 1 gwei of MKT is now 15 gwei of ETH. This is a much more gradual shift from the original purchase price of 1 gwei of MKT for 10 gwei of ETH.

**Comment by rbharath** [comment]
Here's a few test scenarios for this method that we should capture in test cases:

- Scenario 1:
  - `PRICE_FLOOR` is 10 gwei
  - `SPREAD` is 100 (no spread)
  - Creator block size is 1 MKT
  - Investor 1 invests 10 ETH
  - Investor 2 invests 15 ETH
- Scenario 2:
  - `PRICE_FLOOR` is 1 gwei
  - `SPREAD` is 100 (no spread)
  - Creator block size is 1 MKT
  - Investor 1 invests 10 ETH
  - Investor 2 invests 15 ETH
- Scenario 3:
  - `PRICE_FLOOR` is .01 gwei
  - `SPREAD` is 100 (no spread)
  - Creator block size is 1 MKT
  - Investor 1 invests 10 ETH
  - Investor 2 invests 15 ETH
- Scenario 4 (Direct transfer):
  - `PRICE_FLOOR` is .01 gwei
  - `SPREAD` is 100 (no spread)
  - Creator block size is 1 MKT
  - Creator direct transfers 10 ETH into reserve (not via `invest()` but by direct transfer)
  - Investor 1 invests 10 ETH
  - Investor 2 invests 15 ETH

**Comment by rbharath** [comment]
Here's another test case for us to check:

Set up:
- `PRICE_FLOOR` is .001 gwei
- `SPREAD` is 100 (no spread)
- Creator block is 1 MKT
- Creator direct transfers 10 ETH to the reserve 

Scenario A:
- Investor 1 invests 10 ETH
- Investor 1 invests 10 ETH
- Investor 1 invests 10 ETH
- Investor 1 invests 10 ETH
- Investor 1 invests 10 ETH

Scenario B
- Investor 1 invests 50 ETH

The ownership share of investor 1 in both scenarios A and B should be nearly the same.

**Comment by rbharath** [comment]
Here's a third test case that checks the functionality of spread.

- `PRICE_FLOOR` is .001 gwei
- `SPREAD` is `125` (so `25%` spread)
- Creator block is 1 MKT
- Creator direct transfers 10 ETH to reserve
- Investor 1 invests 10 ETH
- Invester 2 invests 10 ETH
- Investor 3 invests 10 ETH
- Investor 4 invests 10 ETH
- Investor 5 invests 10 ETH

We should see `ownership_1 > ownership_2 > ... > ownership_5`

**Comment by robrobbins** [comment]
#98
