### ISSUE TITLE
Change Payment Flow Equations to minimize Dusting

### ISSUE THREAD

**Issue by rbharath** [computablelabs/goest#99]
At present, our percentage splits for makers/datatrust/reserve are limited to be 25/50. This creates a limited set of possible payment flows possible. Taking a closer look at the equations, it looks like it's possible to move terms around and limit the dusting:

### Reserve Payment:
```
res_fee: wei_value = total / (100 / self.parameterizer.getReservePayment())
```
This should be rewritten to
```
res_fee: wei_value = (total*self.parameterizer.getReservePayment()) / 100 
```

https://github.com/computablelabs/goest/blob/master/contracts/Datatrust.vy#L209

### DataTrust Payment:
```
back_fee: wei_value = (self.parameterizer.getCostPerByte() * requested) / (100 / self.parameterizer.getBackendPayment())
```
This should be rewritten to
```
back_fee: wei_value = (self.parameterizer.getCostPerByte() * requested * self.parameterizer.getBackendPayment()) / 100
```

https://github.com/computablelabs/goest/blob/master/contracts/Datatrust.vy#L293

### Maker Payment:
```
maker_fee: wei_value = (self.parameterizer.getCostPerByte() * accessed) / (100 / self.parameterizer.getMakerPayment())
```
This should be rewritten to
```
maker_fee: wei_value = (self.parameterizer.getCostPerByte() * accessed * self.parameterizer.getMakerPayment()) / 100
```

https://github.com/computablelabs/goest/blob/master/contracts/Listing.vy#L174

**Comment by rbharath** [comment]
With these changes in place, we should be able to support arbitrary percentage payments. The dusting that can happen should be non-damaging since even with dusting, we'll never overpay since division by 100 rounds down. (Underpaying is relatively harmless since the dust is < 100 wei which is negligible value)

**Comment by rbharath** [comment]
As one further bit of dust handling, we should change the minting for market creators:

```
minted: uint256 = (maker_fee/price) * 1000000000 # 1Billionth token is the smallest denomination...
```
This should be
```
minted: uint256 = (maker_fee * 1000000000)/price  # 1Billionth token is the smallest denomination...
```
https://github.com/computablelabs/goest/blob/master/contracts/Listing.vy#L181

**Comment by robrobbins** [comment]
#100
